---
kind: Service
apiVersion: v1
metadata:
  name: dlgin
spec:
  selector:
    app: dlgin
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 5000
      # Port accessible outside cluster
      nodePort: 30002
  type: LoadBalancer



---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dlgin
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: dlgin
    spec:
      containers:
        - name: dlgin
          image: seancrwhite/model:v1
          ports:
            - containerPort: 5000