-- MySQL Script generated by MySQL Workbench
-- Wed 03 Jan 2018 02:58:25 PM MST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SONG
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SONG
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SONG` DEFAULT CHARACTER SET utf8 ;
USE `SONG` ;

-- -----------------------------------------------------
-- Table `SONG`.`GENRES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SONG`.`GENRES` ;

CREATE TABLE IF NOT EXISTS `SONG`.`GENRES` (
  `s_id` INT NOT NULL,
  `international` FLOAT NOT NULL,
  `blues` FLOAT NOT NULL,
  `jazz` FLOAT NOT NULL,
  `classical` FLOAT NOT NULL,
  `historic` FLOAT NOT NULL,
  `country` FLOAT NOT NULL,
  `pop` FLOAT NOT NULL,
  `rock` FLOAT NOT NULL,
  `easy_listening` FLOAT NOT NULL,
  `soul_rnb` FLOAT NOT NULL,
  `electronic` FLOAT NOT NULL,
  `folk` FLOAT NOT NULL,
  `spoken_word` FLOAT NOT NULL,
  `hip_hop` FLOAT NOT NULL,
  `experimental` FLOAT NOT NULL,
  `instrumental` FLOAT NOT NULL,
  PRIMARY KEY (`s_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SONG`.`FEATURES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SONG`.`FEATURES` ;

CREATE TABLE IF NOT EXISTS `SONG`.`FEATURES` (
  `s_id` INT NOT NULL,
  `MFCC_1` FLOAT NOT NULL,
  `MFCC_2` FLOAT NOT NULL,
  `MFCC_3` FLOAT NOT NULL,
  `MFCC_4` FLOAT NOT NULL,
  `MFCC_5` FLOAT NOT NULL,
  `MFCC_6` FLOAT NOT NULL,
  `MFCC_7` FLOAT NOT NULL,
  `MFCC_8` FLOAT NOT NULL,
  `MFCC_9` FLOAT NOT NULL,
  `MFCC_10` FLOAT NOT NULL,
  INDEX `fk_FEATURES_1_idx` (`s_id` ASC),
  CONSTRAINT `fk_FEATURES_1`
    FOREIGN KEY (`s_id`)
    REFERENCES `SONG`.`GENRES` (`s_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
